<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CYPRESS Automation Testing Tutorial</name>
   <tag></tag>
   <elementGuidId>ce839b55-704a-43a8-81fc-0e8a9e3abec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PageList2']/div/div/div/div/ul/li[5]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83456faa-b932-48b3-bb81-23d9ba357e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.techlistic.com/p/cypress-automation-testing-tutorial.html</value>
      <webElementGuid>26d87f23-e729-441a-95ac-c12f4e88533b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CYPRESS Automation Testing Tutorial</value>
      <webElementGuid>53dc5ea0-a98b-447e-9979-cdbbf8b3edac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageList2&quot;)/div[@class=&quot;widget-content&quot;]/div[@class=&quot;overflowable-container overflowable-3&quot;]/div[@class=&quot;overflowable-contents&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;tabs&quot;]/li[@class=&quot;overflowable-item&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-content&quot;]/a[1]</value>
      <webElementGuid>251173b6-42b8-4027-9b26-fcb7bd6ebab3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PageList2']/div/div/div/div/ul/li[5]/div/div/a</value>
      <webElementGuid>4749a3f7-6fd8-45d9-9c85-a1d474fe19d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CYPRESS Automation Testing Tutorial')]</value>
      <webElementGuid>00bdc0f5-21ef-442c-91f5-a293c26c0313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CYPRESS'])[1]/following::a[1]</value>
      <webElementGuid>eb583bbb-93ba-4891-85fb-2a0d47df2bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A Complete Guide to API Development'])[1]/following::a[2]</value>
      <webElementGuid>73adebad-f743-4f68-96cf-9d1a5a677ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JMeter'])[1]/preceding::a[1]</value>
      <webElementGuid>78064626-0c6d-4b8d-9ad5-3e943514642a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance Testing with Apache Jmeter'])[1]/preceding::a[2]</value>
      <webElementGuid>60a28b66-c7ce-46dd-a75c-862abbe46f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CYPRESS Automation Testing Tutorial']/parent::*</value>
      <webElementGuid>02cb1351-575f-48c7-af73-e3ae47c255ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.techlistic.com/p/cypress-automation-testing-tutorial.html')])[2]</value>
      <webElementGuid>8a2a597e-0e34-4e3e-a92a-f9b45d638967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/a</value>
      <webElementGuid>f4f41bc3-61a1-4979-9f04-1c5b11fdaa00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.techlistic.com/p/cypress-automation-testing-tutorial.html' and (text() = 'CYPRESS Automation Testing Tutorial' or . = 'CYPRESS Automation Testing Tutorial')]</value>
      <webElementGuid>755c3fb4-b167-4a23-9aa8-83369d22cb0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
