<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mobile App Testing with Emulator</name>
   <tag></tag>
   <elementGuidId>f255003d-07e2-4eca-847c-e4513e0be095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PageList2']/div/div/div/div/ul/li[8]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67e7c373-0e12-4ef2-bd53-ca0a17d44406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.techlistic.com/2020/01/mobile-testing-with-emulator-step-wise.html</value>
      <webElementGuid>bf0074f9-0e02-4b4d-bd19-018b0a3f0ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile App Testing with Emulator</value>
      <webElementGuid>f998318d-5576-4271-b623-f829dfb0c9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageList2&quot;)/div[@class=&quot;widget-content&quot;]/div[@class=&quot;overflowable-container overflowable-3&quot;]/div[@class=&quot;overflowable-contents&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;tabs&quot;]/li[@class=&quot;overflowable-item&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-content&quot;]/a[1]</value>
      <webElementGuid>97cc8261-ca45-4df6-b2ad-b0ea3a5f75ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PageList2']/div/div/div/div/ul/li[8]/div/div/a</value>
      <webElementGuid>ca2117e9-4c79-409c-8f51-261735083a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mobile App Testing with Emulator')]</value>
      <webElementGuid>505df7a6-dab6-4fb3-933c-375a3c3f85c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/following::a[1]</value>
      <webElementGuid>9a6d1e5e-db66-429d-9f71-7c9e933e671f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BDD Tutorial with Python (Behave)'])[1]/following::a[2]</value>
      <webElementGuid>171a95e9-2f94-44d4-b7c6-1150a9a69f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Mobile App Testing Automation Tools'])[1]/preceding::a[1]</value>
      <webElementGuid>a83e47a5-38e3-4907-8435-ab63c06b56ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile IOS Appium Setup'])[1]/preceding::a[2]</value>
      <webElementGuid>58bd4fee-9853-4361-abb2-9b8a27f2e99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobile App Testing with Emulator']/parent::*</value>
      <webElementGuid>f60c8cc9-36f1-4612-89c8-b3eb6cf9d1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.techlistic.com/2020/01/mobile-testing-with-emulator-step-wise.html')]</value>
      <webElementGuid>82bc71a9-8fff-448f-aab1-ee3e7d712c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/div/a</value>
      <webElementGuid>2a25a776-761f-4dd2-aa84-e169841b587d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.techlistic.com/2020/01/mobile-testing-with-emulator-step-wise.html' and (text() = 'Mobile App Testing with Emulator' or . = 'Mobile App Testing with Emulator')]</value>
      <webElementGuid>6613138d-e957-4257-a484-7eefe03b2e1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
