<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Watch on_ytp-next-button ytp-button</name>
   <tag></tag>
   <elementGuidId>b37e6be8-a547-43bb-8db8-af0733ed7c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ytp-next-button.ytp-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[25]/div[2]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e440a809-3389-4e24-8685-54bc6c3f4120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-next-button ytp-button</value>
      <webElementGuid>1f8b90c1-c021-429f-86ee-fa1864a1b48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a28f8454-7bef-4226-81c3-604e75c6c66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-preview</name>
      <type>Main</type>
      <value>https://i1.ytimg.com/vi/i6Op3z72RhQ/mqdefault.jpg</value>
      <webElementGuid>ee5ef1e2-c70a-40ab-8415-85eb33cb2725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-text</name>
      <type>Main</type>
      <value>Selenium IDE Tutorial (No Coding Required) | TECHLISTIC.COM</value>
      <webElementGuid>936d6baa-7bc0-4ada-86ce-f2d587e7c05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.youtube.com/watch?list=PLbFmeIjECE5d27zyfvP9aASQYKauUsdRE&amp;v=i6Op3z72RhQ</value>
      <webElementGuid>cfeb6dba-135b-44af-8400-5b9595f76dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06c1d817-8558-4b6a-a1c3-f4ec0b27e91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next (SHIFT+n)</value>
      <webElementGuid>01e97abb-ec61-4714-89c7-fb459a42c2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-chrome-bottom ytp-volume-slider-active&quot;]/div[@class=&quot;ytp-chrome-controls&quot;]/div[@class=&quot;ytp-left-controls&quot;]/a[@class=&quot;ytp-next-button ytp-button&quot;]</value>
      <webElementGuid>3182afcf-c489-4510-a2d8-6c3d18f5ebc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Selenium Video Tutorials Playlist (__cfdd52</value>
      <webElementGuid>b4eb8550-11ab-4529-9dba-2e486f465437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[25]/div[2]/div/a[2]</value>
      <webElementGuid>318b80b9-2561-4014-b762-bc29593cf0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch on'])[1]/following::a[2]</value>
      <webElementGuid>6752ed3a-0b47-4ff4-b95f-37990e66f164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='An error occurred while retrieving sharing information. Please try again later.'])[1]/following::a[3]</value>
      <webElementGuid>3dcab2cc-f416-4527-91af-27cf5802d6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::a[1]</value>
      <webElementGuid>5519fe83-777e-47d3-adbc-4f858e05b2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[1]/preceding::a[1]</value>
      <webElementGuid>aa8c67b3-d3bd-48c6-aa33-6700910a6ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.youtube.com/watch?list=PLbFmeIjECE5d27zyfvP9aASQYKauUsdRE&amp;v=i6Op3z72RhQ')]</value>
      <webElementGuid>e1fda78f-2339-4a34-a741-c4fc464b9fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]</value>
      <webElementGuid>933dfbb8-1b30-4d6b-bfad-6f29c34d693e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.youtube.com/watch?list=PLbFmeIjECE5d27zyfvP9aASQYKauUsdRE&amp;v=i6Op3z72RhQ']</value>
      <webElementGuid>af85453b-3c02-43b6-a63f-ed93171d33a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
