<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Selenium Video Tutorials Playlist (__cfdd52</name>
   <tag></tag>
   <elementGuidId>3b6c335c-50d8-447d-82ad-cb6c453c7758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post-body-609609522620151455']/div/div[5]/div[3]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>92ab7226-d71e-433e-b62e-2ed98e92c19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture</value>
      <webElementGuid>72ac5338-75c8-4a42-a928-a313fd3b3556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>744adc45-2e7f-4507-b454-1e717f4bd5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>315</value>
      <webElementGuid>940ea912-bb2b-4593-a993-f48b4198bb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ezsrc</name>
      <type>Main</type>
      <value>https://www.youtube-nocookie.com/embed/videoseries?list=PLbFmeIjECE5d27zyfvP9aASQYKauUsdRE</value>
      <webElementGuid>ce329501-19ec-49f5-932e-a1e9b9435771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>YouTube video player</value>
      <webElementGuid>1933e0c9-cebd-445f-b78e-874427abd104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>560</value>
      <webElementGuid>6447a47a-fd64-47d4-a675-94cc291f2472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> ezlazyloaded</value>
      <webElementGuid>49c543c3-ef2c-4bbb-be33-953609df3bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ezoid</name>
      <type>Main</type>
      <value>0.37226539561378336</value>
      <webElementGuid>0dec5104-101f-46da-8dab-35064de4f625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-body-609609522620151455&quot;)/div[1]/div[@class=&quot;separator&quot;]/div[3]/iframe[@class=&quot;ezlazyloaded&quot;]</value>
      <webElementGuid>61f87e29-d490-4eca-85b3-7c2166c2c285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-609609522620151455']/div/div[5]/div[3]/iframe</value>
      <webElementGuid>8211ecba-ec0a-4a31-a872-93eb89a4733b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>078b994a-2629-43d6-a3ec-32c171be1669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'YouTube video player']</value>
      <webElementGuid>372de521-4945-487b-a6dd-4225cd652318</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
