<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Years of Experience_exp</name>
   <tag></tag>
   <elementGuidId>40357cae-f46c-44f6-a822-603ba05661a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exp-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2185dc7b-1e69-414f-96f3-92409801f62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp-1</value>
      <webElementGuid>ae30f906-d9ca-4ad7-ab91-e4910428d11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exp</value>
      <webElementGuid>5fa4a822-5d3f-4ed8-95c3-ee8c4c7b7aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>27cf50b2-1d19-4a68-be40-cb42c8dd3d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>939d68a3-7fba-4ce0-86ab-4d60bdd221f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp-1&quot;)</value>
      <webElementGuid>a3bc9c60-c5f1-4144-bafc-db4ce220ae9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp-1']</value>
      <webElementGuid>a960d42b-2c47-4847-adce-133b4804daa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[14]/input[2]</value>
      <webElementGuid>e53245ed-bf1c-4be2-9d28-ecb5cef8e8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input[2]</value>
      <webElementGuid>47cae934-281c-4e3d-a4ea-0d03a09de517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'exp-1' and @name = 'exp' and @type = 'radio']</value>
      <webElementGuid>1193d244-83db-4829-80e8-cf9df17a5015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
