<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Automation Tools_tool</name>
   <tag></tag>
   <elementGuidId>277fcba6-f4a6-44d8-b94e-ed7ee217b412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tool-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tool-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5b849ba-86fd-4943-bc3a-c00d82a2d5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-2</value>
      <webElementGuid>71ffdbb4-59f1-49bc-9d6b-b9b774882e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tool</value>
      <webElementGuid>3d6a88a9-2185-47b0-8908-923eb20d5b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6c27136e-7c1a-4f7a-aa80-3c76fb9aa48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Selenium Webdriver</value>
      <webElementGuid>dd2aa725-680a-4762-b276-81a360d1cad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-2&quot;)</value>
      <webElementGuid>adc4e3e8-69f0-4ad1-9564-d68556e12a84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tool-2']</value>
      <webElementGuid>af378e6d-c679-4c15-9e60-063fcb443a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[22]/input[3]</value>
      <webElementGuid>c043433a-5e39-4a39-982e-98f26aa42bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/input[3]</value>
      <webElementGuid>c262ffa6-640a-4c3e-b2da-bee190d15af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tool-2' and @name = 'tool' and @type = 'checkbox']</value>
      <webElementGuid>d873c04a-9eb6-4126-a08f-a18b3a2b015f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
