<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Browser CommandsNavigation CommandsS_69f390</name>
   <tag></tag>
   <elementGuidId>f699b54a-2f34-4710-9f39-31d05c8c818c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selenium_commands</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selenium_commands']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc752c62-1bdf-4688-98e5-61156c22f25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>20d7ca72-1717-4ce5-a8de-59021e17caca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selenium_commands</value>
      <webElementGuid>5dfbbe7a-b27c-4ffd-b229-e89b076b4ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selenium_commands</value>
      <webElementGuid>af03f49e-562e-4516-92a0-e6a7eecd6b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands</value>
      <webElementGuid>3af30d44-bd6c-42f9-9b2e-2bbb07664d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selenium_commands&quot;)</value>
      <webElementGuid>d03cf7ee-a7a1-475f-b054-651d1c088bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selenium_commands']</value>
      <webElementGuid>e64c21b5-9d6c-4050-9516-991910799d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[27]/div[2]/select</value>
      <webElementGuid>7bf5c7bf-a052-4893-b6e8-118422ae649a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Commands'])[1]/following::select[1]</value>
      <webElementGuid>243b4e77-e01e-491d-b411-cef570449cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continents'])[1]/following::select[2]</value>
      <webElementGuid>23b8cd5c-6ce6-4e61-a523-dfe473ce8663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Image'])[1]/preceding::select[1]</value>
      <webElementGuid>4efbee12-9de9-430c-896e-3822002d2336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/select</value>
      <webElementGuid>2f7caaa8-43e4-491e-a955-78f7521391a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selenium_commands' and @name = 'selenium_commands' and (text() = 'Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands' or . = 'Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands')]</value>
      <webElementGuid>fe42f512-2102-4684-b02a-ed70408b6efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
